-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE products ADD COLUMN IF NOT EXISTS field1 TEXT, ADD COLUMN IF NOT EXISTS field2 TEXT, ADD COLUMN IF NOT EXISTS field3 TEXT, ADD COLUMN IF NOT EXISTS field4 TEXT, ADD COLUMN IF NOT EXISTS field5 TEXT;
