-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE vessels (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), vessel_id VARCHAR(50) NOT NULL UNIQUE, vessel_name VARCHAR(200), imo_number VARCHAR(20), voyage_number VARCHAR(50), carrier_id UUID REFERENCES carriers(id), schedule TEXT, active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
