-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE template_subject_fields (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 field_key TEXT NOT NULL UNIQUE,
 label TEXT NOT NULL,
 field_type TEXT NOT NULL CHECK (field_type IN ('select', 'multiselect', 'text')),
 source TEXT,
 required BOOLEAN NOT NULL DEFAULT false,
 enabled BOOLEAN NOT NULL DEFAULT true,
 sort_order INTEGER NOT NULL DEFAULT 0,
 options JSONB,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE template_subject_fields ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_template_subject_fields ON template_subject_fields FOR SELECT USING (true);
CREATE POLICY anon_insert_template_subject_fields ON template_subject_fields FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_template_subject_fields ON template_subject_fields FOR UPDATE USING (true);
CREATE POLICY anon_delete_template_subject_fields ON template_subject_fields FOR DELETE USING (true);

