-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE equipment (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), equipment_id VARCHAR(50) NOT NULL UNIQUE, equipment_name VARCHAR(200), equipment_type VARCHAR(20) CHECK (equipment_type IN ('20GP', '40GP', '40HC', '45HC', '20RF', '40RF', 'Tank', 'Flat Rack', 'Open Top', 'Other')), teu_capacity INTEGER, length DECIMAL(10,2), height DECIMAL(10,2), max_weight DECIMAL(10,2), unit_type VARCHAR(10) CHECK (unit_type IN ('FCL', 'LCL')), owner VARCHAR(100), active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
