-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE fallback_assignment_rules (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 condition TEXT NOT NULL,
 fallback_queue TEXT NOT NULL,
 escalation_role TEXT NOT NULL,
 escalation_sla TEXT NOT NULL,
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE fallback_assignment_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_fallback_assignment_rules ON fallback_assignment_rules FOR SELECT USING (true);
CREATE POLICY anon_insert_fallback_assignment_rules ON fallback_assignment_rules FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_fallback_assignment_rules ON fallback_assignment_rules FOR UPDATE USING (true);
CREATE POLICY anon_delete_fallback_assignment_rules ON fallback_assignment_rules FOR DELETE USING (true);

