-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE milestone_tasks (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 template_id UUID NOT NULL REFERENCES process_templates(id) ON DELETE CASCADE,
 milestone_id UUID NOT NULL REFERENCES milestones(id) ON DELETE CASCADE,
 customer TEXT,
 task_name TEXT NOT NULL,
 task_type TEXT,
 sla_type_id UUID,
 required_files TEXT,
 automation TEXT DEFAULT 'Manual' CHECK (automation IN ('Manual', 'Semi-auto', 'Auto')),
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Draft')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE milestone_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_milestone_tasks ON milestone_tasks FOR SELECT USING (true);
CREATE POLICY anon_insert_milestone_tasks ON milestone_tasks FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_milestone_tasks ON milestone_tasks FOR UPDATE USING (true);
CREATE POLICY anon_delete_milestone_tasks ON milestone_tasks FOR DELETE USING (true);

