-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE iam_users (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_number VARCHAR(50) UNIQUE NOT NULL,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(255) UNIQUE,
 phone VARCHAR(20),
 role_ids UUID[],
 organization_ids UUID[],
 active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE iam_users ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_iam_users ON iam_users FOR SELECT USING (true);
CREATE POLICY anon_insert_iam_users ON iam_users FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_iam_users ON iam_users FOR UPDATE USING (true);
CREATE POLICY anon_delete_iam_users ON iam_users FOR DELETE USING (true);

