-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE carriers ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_all_carriers ON carriers FOR ALL USING (true) WITH CHECK (true); ALTER TABLE locations ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_all_locations ON locations FOR ALL USING (true) WITH CHECK (true); ALTER TABLE products ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_all_products ON products FOR ALL USING (true) WITH CHECK (true); ALTER TABLE equipment ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_all_equipment ON equipment FOR ALL USING (true) WITH CHECK (true); ALTER TABLE vessels ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_all_vessels ON vessels FOR ALL USING (true) WITH CHECK (true);
