-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE clients ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_all_clients ON clients FOR ALL USING (true) WITH CHECK (true);
