-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE business_partners (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_code VARCHAR(10) NOT NULL UNIQUE, organization_name VARCHAR(200) NOT NULL, address_line1 VARCHAR(200), address_line2 VARCHAR(200), city VARCHAR(100), state_province VARCHAR(100), postal_code VARCHAR(20), country VARCHAR(100), organization_type VARCHAR(20) NOT NULL CHECK (organization_type IN ('Supplier', 'Producer', 'Trucker')), client_id UUID REFERENCES clients(id), contact_person VARCHAR(100), contact_email VARCHAR(200), active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
