-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE team_assignment_rules (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 customer TEXT,
 origin_region TEXT,
 destination_region TEXT,
 pol TEXT,
 pod TEXT,
 lane TEXT,
 transport_mode TEXT,
 exception_type TEXT,
 priority TEXT NOT NULL CHECK (priority IN ('High', 'Medium', 'Low')),
 target_team TEXT NOT NULL,
 assigner_role TEXT NOT NULL CHECK (assigner_role IN ('Department Head', 'Operation Manager', 'Admin')),
 scope_owner_role TEXT NOT NULL CHECK (scope_owner_role IN ('Department Head', 'Admin')),
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Draft')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE team_assignment_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_team_assignment_rules ON team_assignment_rules FOR SELECT USING (true);
CREATE POLICY anon_insert_team_assignment_rules ON team_assignment_rules FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_team_assignment_rules ON team_assignment_rules FOR UPDATE USING (true);
CREATE POLICY anon_delete_team_assignment_rules ON team_assignment_rules FOR DELETE USING (true);

