-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE reason_codes (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 code TEXT NOT NULL UNIQUE,
 name TEXT NOT NULL,
 scenario TEXT,
 remark_required BOOLEAN DEFAULT false,
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE reason_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_reason_codes ON reason_codes FOR SELECT USING (true);
CREATE POLICY anon_insert_reason_codes ON reason_codes FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_reason_codes ON reason_codes FOR UPDATE USING (true);
CREATE POLICY anon_delete_reason_codes ON reason_codes FOR DELETE USING (true);

