-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE iam_organizations (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 org_number VARCHAR(50) UNIQUE NOT NULL,
 org_name VARCHAR(100) NOT NULL,
 org_type VARCHAR(50) NOT NULL,
 parent_id UUID REFERENCES iam_organizations(id),
 description TEXT,
 active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE iam_organizations ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_iam_organizations ON iam_organizations FOR SELECT USING (true);
CREATE POLICY anon_insert_iam_organizations ON iam_organizations FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_iam_organizations ON iam_organizations FOR UPDATE USING (true);
CREATE POLICY anon_delete_iam_organizations ON iam_organizations FOR DELETE USING (true);

