-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE iam_roles (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 role_number VARCHAR(50) UNIQUE NOT NULL,
 role_id VARCHAR(50) UNIQUE NOT NULL,
 role_name VARCHAR(100) NOT NULL,
 role_type VARCHAR(50) NOT NULL,
 description TEXT,
 permissions JSONB DEFAULT '{}',
 active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE iam_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_iam_roles ON iam_roles FOR SELECT USING (true);
CREATE POLICY anon_insert_iam_roles ON iam_roles FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_iam_roles ON iam_roles FOR UPDATE USING (true);
CREATE POLICY anon_delete_iam_roles ON iam_roles FOR DELETE USING (true);

