-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE notification_templates (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 template_name TEXT NOT NULL,
 scenario TEXT NOT NULL,
 subject TEXT NOT NULL,
 body TEXT NOT NULL,
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE notification_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_notification_templates ON notification_templates FOR SELECT USING (true);
CREATE POLICY anon_insert_notification_templates ON notification_templates FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_notification_templates ON notification_templates FOR UPDATE USING (true);
CREATE POLICY anon_delete_notification_templates ON notification_templates FOR DELETE USING (true);

