-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE user_assignment_rules (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 team_id TEXT NOT NULL,
 template_id UUID,
 milestone_id UUID,
 task_id UUID,
 task_type TEXT,
 role_required TEXT,
 target_user TEXT NOT NULL,
 backup_user TEXT,
 workload_strategy TEXT NOT NULL CHECK (workload_strategy IN ('Round Robin', 'Least Loaded', 'Manual')),
 assigner_role TEXT NOT NULL CHECK (assigner_role IN ('Team Leader', 'Team Manager')),
 scope_owner_role TEXT NOT NULL CHECK (scope_owner_role IN ('Team Leader')),
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Draft')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE user_assignment_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_user_assignment_rules ON user_assignment_rules FOR SELECT USING (true);
CREATE POLICY anon_insert_user_assignment_rules ON user_assignment_rules FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_user_assignment_rules ON user_assignment_rules FOR UPDATE USING (true);
CREATE POLICY anon_delete_user_assignment_rules ON user_assignment_rules FOR DELETE USING (true);

