-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE milestones (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 template_id UUID NOT NULL REFERENCES process_templates(id) ON DELETE CASCADE,
 milestone_seq INTEGER NOT NULL,
 milestone_name TEXT NOT NULL,
 predecessor TEXT,
 sla_type_id UUID,
 skippable TEXT DEFAULT 'No' CHECK (skippable IN ('Yes', 'No')),
 skip_condition TEXT,
 required_files TEXT,
 automation TEXT DEFAULT 'Manual' CHECK (automation IN ('Manual', 'Semi-auto', 'Auto')),
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE milestones ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_milestones ON milestones FOR SELECT USING (true);
CREATE POLICY anon_insert_milestones ON milestones FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_milestones ON milestones FOR UPDATE USING (true);
CREATE POLICY anon_delete_milestones ON milestones FOR DELETE USING (true);

