-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE transport_modes (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 code TEXT NOT NULL UNIQUE,
 name TEXT NOT NULL,
 applicable_region TEXT,
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE transport_modes ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_transport_modes ON transport_modes FOR SELECT USING (true);
CREATE POLICY anon_insert_transport_modes ON transport_modes FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_transport_modes ON transport_modes FOR UPDATE USING (true);
CREATE POLICY anon_delete_transport_modes ON transport_modes FOR DELETE USING (true);

