-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id VARCHAR(50) NOT NULL UNIQUE, product_code VARCHAR(100), product_description TEXT, commodity_code VARCHAR(20), hazardous_material_flag BOOLEAN DEFAULT false, un_number VARCHAR(20), dangerous_goods_class VARCHAR(10), packaging_group VARCHAR(10), temperature_requirement VARCHAR(50), default_weight DECIMAL(10,2), default_dimensions VARCHAR(50), active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
