-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE locations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), location_id VARCHAR(50) NOT NULL UNIQUE, un_locode VARCHAR(10), location_name VARCHAR(200) NOT NULL, location_type VARCHAR(20) NOT NULL CHECK (location_type IN ('Port', 'Airport', 'City')), country VARCHAR(100), region VARCHAR(100), active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
