-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE sla_type_configs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 sla_rule_base_date_code TEXT NOT NULL,
 sla_rule_direction TEXT NOT NULL CHECK (sla_rule_direction IN ('Before', 'After')),
 sla_rule_offset_value INTEGER NOT NULL DEFAULT 0,
 sla_rule_offset_unit TEXT NOT NULL CHECK (sla_rule_offset_unit IN ('Hours', 'Days', 'Business Days', 'Months')),
 calendar_code TEXT,
 object_scope TEXT NOT NULL CHECK (object_scope IN ('Task', 'Milestone', 'Booking', 'Shipment')),
 reminder_threshold INTEGER,
 reminder_unit TEXT CHECK (reminder_unit IN ('Hours', 'Days', 'Business Days', 'Months')),
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE sla_type_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_sla_type_configs ON sla_type_configs FOR SELECT USING (true);
CREATE POLICY anon_insert_sla_type_configs ON sla_type_configs FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_sla_type_configs ON sla_type_configs FOR UPDATE USING (true);
CREATE POLICY anon_delete_sla_type_configs ON sla_type_configs FOR DELETE USING (true);

