-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE exception_types (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 code TEXT NOT NULL UNIQUE,
 name TEXT NOT NULL,
 severity TEXT NOT NULL CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
 default_sla TEXT,
 escalation BOOLEAN DEFAULT false,
 status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE exception_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_exception_types ON exception_types FOR SELECT USING (true);
CREATE POLICY anon_insert_exception_types ON exception_types FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_exception_types ON exception_types FOR UPDATE USING (true);
CREATE POLICY anon_delete_exception_types ON exception_types FOR DELETE USING (true);

