-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE process_templates (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 template_name TEXT NOT NULL,
 customer TEXT,
 pol TEXT,
 pod TEXT,
 lane TEXT,
 transport_mode TEXT,
 region TEXT,
 subject_values JSONB,
 effective_date DATE,
 version TEXT DEFAULT '1.0',
 tags TEXT,
 status TEXT DEFAULT 'Draft' CHECK (status IN ('Active', 'Inactive', 'Draft')),
 remark TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE process_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_process_templates ON process_templates FOR SELECT USING (true);
CREATE POLICY anon_insert_process_templates ON process_templates FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_process_templates ON process_templates FOR UPDATE USING (true);
CREATE POLICY anon_delete_process_templates ON process_templates FOR DELETE USING (true);

