-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE carriers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), carrier_code VARCHAR(50) NOT NULL UNIQUE, carrier_name VARCHAR(200) NOT NULL, scac VARCHAR(10), mode VARCHAR(20) NOT NULL CHECK (mode IN ('OCEAN', 'AIR', 'Truck')), country VARCHAR(100), contact_person VARCHAR(100), contact_email VARCHAR(200), notes TEXT, active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
