// ============================================
// 此文件由 Meoo Cloud 自动生成，请勿修改
// This file is auto-generated by Meoo Cloud, DO NOT MODIFY
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      business_partners: {
        Row: {
          active: boolean | null
          address_line1: string | null
          address_line2: string | null
          city: string | null
          client_id: string | null
          contact_email: string | null
          contact_person: string | null
          country: string | null
          created_at: string | null
          id: string
          organization_code: string
          organization_name: string
          organization_type: string
          postal_code: string | null
          state_province: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          address_line1?: string | null
          address_line2?: string | null
          city?: string | null
          client_id?: string | null
          contact_email?: string | null
          contact_person?: string | null
          country?: string | null
          created_at?: string | null
          id?: string
          organization_code: string
          organization_name: string
          organization_type: string
          postal_code?: string | null
          state_province?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          address_line1?: string | null
          address_line2?: string | null
          city?: string | null
          client_id?: string | null
          contact_email?: string | null
          contact_person?: string | null
          country?: string | null
          created_at?: string | null
          id?: string
          organization_code?: string
          organization_name?: string
          organization_type?: string
          postal_code?: string | null
          state_province?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "business_partners_client_id_fkey"
            columns: ["client_id"]
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
        ]
      }
      carriers: {
        Row: {
          active: boolean | null
          carrier_code: string
          carrier_name: string
          contact_email: string | null
          contact_person: string | null
          country: string | null
          created_at: string | null
          id: string
          mode: string
          notes: string | null
          scac: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          carrier_code: string
          carrier_name: string
          contact_email?: string | null
          contact_person?: string | null
          country?: string | null
          created_at?: string | null
          id?: string
          mode: string
          notes?: string | null
          scac?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          carrier_code?: string
          carrier_name?: string
          contact_email?: string | null
          contact_person?: string | null
          country?: string | null
          created_at?: string | null
          id?: string
          mode?: string
          notes?: string | null
          scac?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      clients: {
        Row: {
          active: boolean | null
          address_line1: string | null
          address_line2: string | null
          billing_address: string | null
          city: string | null
          client_id: number
          client_code: string
          client_name: string
          client_type: string
          contact_email: string | null
          contact_person: string | null
          contact_phone: string | null
          country: string | null
          created_by: string | null
          created_at: string | null
          credit_limit: number | null
          discount_profile: string | null
          id: string
          industry_sector: string | null
          invoice_currency: string
          invoice_format: string | null
          invoice_legal_entity: string
          notes: string | null
          operational_country: string | null
          payment_terms: string | null
          postal_code: string | null
          state_province: string | null
          status: string
          tax_registration_number: string | null
          timezone: string | null
          updated_at: string | null
          updated_by: string | null
        }
        Insert: {
          active?: boolean | null
          address_line1?: string | null
          address_line2?: string | null
          billing_address?: string | null
          city?: string | null
          client_id?: number
          client_code: string
          client_name: string
          client_type: string
          contact_email?: string | null
          contact_person?: string | null
          contact_phone?: string | null
          country?: string | null
          created_by?: string | null
          created_at?: string | null
          credit_limit?: number | null
          discount_profile?: string | null
          id?: string
          industry_sector?: string | null
          invoice_currency: string
          invoice_format?: string | null
          invoice_legal_entity: string
          notes?: string | null
          operational_country?: string | null
          payment_terms?: string | null
          postal_code?: string | null
          state_province?: string | null
          status?: string
          tax_registration_number?: string | null
          timezone?: string | null
          updated_at?: string | null
          updated_by?: string | null
        }
        Update: {
          active?: boolean | null
          address_line1?: string | null
          address_line2?: string | null
          billing_address?: string | null
          city?: string | null
          client_id?: number
          client_code?: string
          client_name?: string
          client_type?: string
          contact_email?: string | null
          contact_person?: string | null
          contact_phone?: string | null
          country?: string | null
          created_by?: string | null
          created_at?: string | null
          credit_limit?: number | null
          discount_profile?: string | null
          id?: string
          industry_sector?: string | null
          invoice_currency?: string
          invoice_format?: string | null
          invoice_legal_entity?: string
          notes?: string | null
          operational_country?: string | null
          payment_terms?: string | null
          postal_code?: string | null
          state_province?: string | null
          status?: string
          tax_registration_number?: string | null
          timezone?: string | null
          updated_at?: string | null
          updated_by?: string | null
        }
        Relationships: []
      }
      equipment: {
        Row: {
          active: boolean | null
          created_at: string | null
          equipment_id: string
          equipment_name: string | null
          equipment_type: string | null
          height: number | null
          id: string
          length: number | null
          max_weight: number | null
          owner: string | null
          teu_capacity: number | null
          unit_type: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          created_at?: string | null
          equipment_id: string
          equipment_name?: string | null
          equipment_type?: string | null
          height?: number | null
          id?: string
          length?: number | null
          max_weight?: number | null
          owner?: string | null
          teu_capacity?: number | null
          unit_type?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          created_at?: string | null
          equipment_id?: string
          equipment_name?: string | null
          equipment_type?: string | null
          height?: number | null
          id?: string
          length?: number | null
          max_weight?: number | null
          owner?: string | null
          teu_capacity?: number | null
          unit_type?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      exception_types: {
        Row: {
          code: string
          created_at: string
          default_sla: string | null
          escalation: boolean | null
          id: string
          name: string
          remark: string | null
          severity: string
          status: string | null
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          default_sla?: string | null
          escalation?: boolean | null
          id?: string
          name: string
          remark?: string | null
          severity: string
          status?: string | null
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          default_sla?: string | null
          escalation?: boolean | null
          id?: string
          name?: string
          remark?: string | null
          severity?: string
          status?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      fallback_assignment_rules: {
        Row: {
          condition: string
          created_at: string
          escalation_role: string
          escalation_sla: string
          fallback_queue: string
          id: string
          remark: string | null
          status: string | null
          updated_at: string
        }
        Insert: {
          condition: string
          created_at?: string
          escalation_role: string
          escalation_sla: string
          fallback_queue: string
          id?: string
          remark?: string | null
          status?: string | null
          updated_at?: string
        }
        Update: {
          condition?: string
          created_at?: string
          escalation_role?: string
          escalation_sla?: string
          fallback_queue?: string
          id?: string
          remark?: string | null
          status?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      iam_organizations: {
        Row: {
          active: boolean | null
          country: string | null
          created_at: string | null
          description: string | null
          external_org_id: string | null
          function_team: string | null
          id: string
          org_name: string
          org_number: string
          org_type: string
          owner: string | null
          parent_id: string | null
          region: string | null
          remark: string | null
          source_system: string | null
          sync_status: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          country?: string | null
          created_at?: string | null
          description?: string | null
          external_org_id?: string | null
          function_team?: string | null
          id?: string
          org_name: string
          org_number: string
          org_type: string
          owner?: string | null
          parent_id?: string | null
          region?: string | null
          remark?: string | null
          source_system?: string | null
          sync_status?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          country?: string | null
          created_at?: string | null
          description?: string | null
          external_org_id?: string | null
          function_team?: string | null
          id?: string
          org_name?: string
          org_number?: string
          org_type?: string
          owner?: string | null
          parent_id?: string | null
          region?: string | null
          remark?: string | null
          source_system?: string | null
          sync_status?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "iam_organizations_parent_id_fkey"
            columns: ["parent_id"]
            referencedRelation: "iam_organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organization_data_scopes: {
        Row: {
          active: boolean | null
          all_data: boolean | null
          client_ids: string[] | null
          countries: string[] | null
          created_at: string | null
          id: string
          organization_id: string
          regions: string[] | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          all_data?: boolean | null
          client_ids?: string[] | null
          countries?: string[] | null
          created_at?: string | null
          id?: string
          organization_id: string
          regions?: string[] | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          all_data?: boolean | null
          client_ids?: string[] | null
          countries?: string[] | null
          created_at?: string | null
          id?: string
          organization_id?: string
          regions?: string[] | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "organization_data_scopes_organization_id_fkey"
            columns: ["organization_id"]
            referencedRelation: "iam_organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      region_country_configs: {
        Row: {
          active: boolean | null
          country_code: string
          country_name: string
          created_at: string | null
          id: string
          region: string
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          country_code: string
          country_name: string
          created_at?: string | null
          id?: string
          region: string
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          country_code?: string
          country_name?: string
          created_at?: string | null
          id?: string
          region?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      iam_roles: {
        Row: {
          active: boolean | null
          created_at: string | null
          description: string | null
          id: string
          permissions: Json | null
          role_id: string
          role_name: string
          role_number: string
          role_type: string
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          created_at?: string | null
          description?: string | null
          id?: string
          permissions?: Json | null
          role_id: string
          role_name: string
          role_number: string
          role_type: string
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          created_at?: string | null
          description?: string | null
          id?: string
          permissions?: Json | null
          role_id?: string
          role_name?: string
          role_number?: string
          role_type?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      iam_users: {
        Row: {
          active: boolean | null
          created_at: string | null
          email: string | null
          id: string
          name: string
          organization_ids: string[] | null
          phone: string | null
          role_ids: string[] | null
          updated_at: string | null
          user_number: string
        }
        Insert: {
          active?: boolean | null
          created_at?: string | null
          email?: string | null
          id?: string
          name: string
          organization_ids?: string[] | null
          phone?: string | null
          role_ids?: string[] | null
          updated_at?: string | null
          user_number: string
        }
        Update: {
          active?: boolean | null
          created_at?: string | null
          email?: string | null
          id?: string
          name?: string
          organization_ids?: string[] | null
          phone?: string | null
          role_ids?: string[] | null
          updated_at?: string | null
          user_number?: string
        }
        Relationships: []
      }
      locations: {
        Row: {
          active: boolean | null
          country: string | null
          created_at: string | null
          id: string
          location_id: string
          location_name: string
          location_type: string
          region: string | null
          un_locode: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          country?: string | null
          created_at?: string | null
          id?: string
          location_id: string
          location_name: string
          location_type: string
          region?: string | null
          un_locode?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          country?: string | null
          created_at?: string | null
          id?: string
          location_id?: string
          location_name?: string
          location_type?: string
          region?: string | null
          un_locode?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      milestone_tasks: {
        Row: {
          automation: string | null
          created_at: string
          customer: string | null
          id: string
          milestone_id: string
          remark: string | null
          required_files: string | null
          sla_type_id: string | null
          status: string | null
          task_name: string
          task_type: string | null
          template_id: string
          updated_at: string
        }
        Insert: {
          automation?: string | null
          created_at?: string
          customer?: string | null
          id?: string
          milestone_id: string
          remark?: string | null
          required_files?: string | null
          sla_type_id?: string | null
          status?: string | null
          task_name: string
          task_type?: string | null
          template_id: string
          updated_at?: string
        }
        Update: {
          automation?: string | null
          created_at?: string
          customer?: string | null
          id?: string
          milestone_id?: string
          remark?: string | null
          required_files?: string | null
          sla_type_id?: string | null
          status?: string | null
          task_name?: string
          task_type?: string | null
          template_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "milestone_tasks_milestone_id_fkey"
            columns: ["milestone_id"]
            referencedRelation: "milestones"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestone_tasks_template_id_fkey"
            columns: ["template_id"]
            referencedRelation: "process_templates"
            referencedColumns: ["id"]
          },
        ]
      }
      milestones: {
        Row: {
          automation: string | null
          created_at: string
          id: string
          milestone_name: string
          milestone_seq: number
          predecessor: string | null
          required_files: string | null
          skip_condition: string | null
          skippable: string | null
          sla_type_id: string | null
          status: string | null
          template_id: string
          updated_at: string
        }
        Insert: {
          automation?: string | null
          created_at?: string
          id?: string
          milestone_name: string
          milestone_seq: number
          predecessor?: string | null
          required_files?: string | null
          skip_condition?: string | null
          skippable?: string | null
          sla_type_id?: string | null
          status?: string | null
          template_id: string
          updated_at?: string
        }
        Update: {
          automation?: string | null
          created_at?: string
          id?: string
          milestone_name?: string
          milestone_seq?: number
          predecessor?: string | null
          required_files?: string | null
          skip_condition?: string | null
          skippable?: string | null
          sla_type_id?: string | null
          status?: string | null
          template_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "milestones_template_id_fkey"
            columns: ["template_id"]
            referencedRelation: "process_templates"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_templates: {
        Row: {
          body: string
          created_at: string
          id: string
          remark: string | null
          scenario: string
          status: string | null
          subject: string
          template_name: string
          updated_at: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          remark?: string | null
          scenario: string
          status?: string | null
          subject: string
          template_name: string
          updated_at?: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          remark?: string | null
          scenario?: string
          status?: string | null
          subject?: string
          template_name?: string
          updated_at?: string
        }
        Relationships: []
      }
      process_templates: {
        Row: {
          created_at: string
          customer: string | null
          effective_date: string | null
          id: string
          lane: string | null
          pod: string | null
          pol: string | null
          region: string | null
          remark: string | null
          status: string | null
          subject_values: Json | null
          tags: string | null
          template_name: string
          transport_mode: string | null
          updated_at: string
          version: string | null
        }
        Insert: {
          created_at?: string
          customer?: string | null
          effective_date?: string | null
          id?: string
          lane?: string | null
          pod?: string | null
          pol?: string | null
          region?: string | null
          remark?: string | null
          status?: string | null
          subject_values?: Json | null
          tags?: string | null
          template_name: string
          transport_mode?: string | null
          updated_at?: string
          version?: string | null
        }
        Update: {
          created_at?: string
          customer?: string | null
          effective_date?: string | null
          id?: string
          lane?: string | null
          pod?: string | null
          pol?: string | null
          region?: string | null
          remark?: string | null
          status?: string | null
          subject_values?: Json | null
          tags?: string | null
          template_name?: string
          transport_mode?: string | null
          updated_at?: string
          version?: string | null
        }
        Relationships: []
      }
      products: {
        Row: {
          active: boolean | null
          commodity_code: string | null
          created_at: string | null
          dangerous_goods_class: string | null
          default_dimensions: string | null
          default_weight: number | null
          field1: string | null
          field2: string | null
          field3: string | null
          field4: string | null
          field5: string | null
          hazardous_material_flag: boolean | null
          id: string
          packaging_group: string | null
          product_code: string | null
          product_description: string | null
          product_id: string
          temperature_requirement: string | null
          un_number: string | null
          updated_at: string | null
        }
        Insert: {
          active?: boolean | null
          commodity_code?: string | null
          created_at?: string | null
          dangerous_goods_class?: string | null
          default_dimensions?: string | null
          default_weight?: number | null
          field1?: string | null
          field2?: string | null
          field3?: string | null
          field4?: string | null
          field5?: string | null
          hazardous_material_flag?: boolean | null
          id?: string
          packaging_group?: string | null
          product_code?: string | null
          product_description?: string | null
          product_id: string
          temperature_requirement?: string | null
          un_number?: string | null
          updated_at?: string | null
        }
        Update: {
          active?: boolean | null
          commodity_code?: string | null
          created_at?: string | null
          dangerous_goods_class?: string | null
          default_dimensions?: string | null
          default_weight?: number | null
          field1?: string | null
          field2?: string | null
          field3?: string | null
          field4?: string | null
          field5?: string | null
          hazardous_material_flag?: boolean | null
          id?: string
          packaging_group?: string | null
          product_code?: string | null
          product_description?: string | null
          product_id?: string
          temperature_requirement?: string | null
          un_number?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      reason_codes: {
        Row: {
          code: string
          created_at: string
          id: string
          name: string
          remark: string | null
          remark_required: boolean | null
          scenario: string | null
          status: string | null
          updated_at: string
        }
        Insert: {
          code: string
          created_at?: string
          id?: string
          name: string
          remark?: string | null
          remark_required?: boolean | null
          scenario?: string | null
          status?: string | null
          updated_at?: string
        }
        Update: {
          code?: string
          created_at?: string
          id?: string
          name?: string
          remark?: string | null
          remark_required?: boolean | null
          scenario?: string | null
          status?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      sla_type_configs: {
        Row: {
          calendar_code: string | null
          created_at: string
          id: string
          object_scope: string
          remark: string | null
          reminder_threshold: number | null
          reminder_unit: string | null
          sla_rule_base_date_code: string
          sla_rule_direction: string
          sla_rule_offset_unit: string
          sla_rule_offset_value: number
          status: string | null
          updated_at: string
        }
        Insert: {
          calendar_code?: string | null
          created_at?: string
          id?: string
          object_scope: string
          remark?: string | null
          reminder_threshold?: number | null
          reminder_unit?: string | null
          sla_rule_base_date_code: string
          sla_rule_direction: string
          sla_rule_offset_unit: string
          sla_rule_offset_value?: number
          status?: string | null
          updated_at?: string
        }
        Update: {
          calendar_code?: string | null
          created_at?: string
          id?: string
          object_scope?: string
          remark?: string | null
          reminder_threshold?: number | null
          reminder_unit?: string | null
          sla_rule_base_date_code?: string
          sla_rule_direction?: string
          sla_rule_offset_unit?: string
          sla_rule_offset_value?: number
          status?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      team_assignment_rules: {
        Row: {
          assigner_role: string
          created_at: string
          customer: string | null
          destination_region: string | null
          exception_type: string | null
          id: string
          lane: string | null
          origin_region: string | null
          pod: string | null
          pol: string | null
          priority: string
          remark: string | null
          scope_owner_role: string
          status: string | null
          target_team: string
          transport_mode: string | null
          updated_at: string
        }
        Insert: {
          assigner_role: string
          created_at?: string
          customer?: string | null
          destination_region?: string | null
          exception_type?: string | null
          id?: string
          lane?: string | null
          origin_region?: string | null
          pod?: string | null
          pol?: string | null
          priority: string
          remark?: string | null
          scope_owner_role: string
          status?: string | null
          target_team: string
          transport_mode?: string | null
          updated_at?: string
        }
        Update: {
          assigner_role?: string
          created_at?: string
          customer?: string | null
          destination_region?: string | null
          exception_type?: string | null
          id?: string
          lane?: string | null
          origin_region?: string | null
          pod?: string | null
          pol?: string | null
          priority?: string
          remark?: string | null
          scope_owner_role?: string
          status?: string | null
          target_team?: string
          transport_mode?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      template_subject_fields: {
        Row: {
          created_at: string
          enabled: boolean
          field_key: string
          field_type: string
          id: string
          label: string
          options: Json | null
          required: boolean
          sort_order: number
          source: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          enabled?: boolean
          field_key: string
          field_type: string
          id?: string
          label: string
          options?: Json | null
          required?: boolean
          sort_order?: number
          source?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          enabled?: boolean
          field_key?: string
          field_type?: string
          id?: string
          label?: string
          options?: Json | null
          required?: boolean
          sort_order?: number
          source?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      transport_modes: {
        Row: {
          applicable_region: string | null
          code: string
          created_at: string
          id: string
          name: string
          remark: string | null
          status: string | null
          updated_at: string
        }
        Insert: {
          applicable_region?: string | null
          code: string
          created_at?: string
          id?: string
          name: string
          remark?: string | null
          status?: string | null
          updated_at?: string
        }
        Update: {
          applicable_region?: string | null
          code?: string
          created_at?: string
          id?: string
          name?: string
          remark?: string | null
          status?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      user_assignment_rules: {
        Row: {
          assigner_role: string
          backup_user: string | null
          created_at: string
          id: string
          milestone_id: string | null
          remark: string | null
          role_required: string | null
          scope_owner_role: string
          status: string | null
          target_user: string
          task_id: string | null
          task_type: string | null
          team_id: string
          template_id: string | null
          updated_at: string
          workload_strategy: string
        }
        Insert: {
          assigner_role: string
          backup_user?: string | null
          created_at?: string
          id?: string
          milestone_id?: string | null
          remark?: string | null
          role_required?: string | null
          scope_owner_role: string
          status?: string | null
          target_user: string
          task_id?: string | null
          task_type?: string | null
          team_id: string
          template_id?: string | null
          updated_at?: string
          workload_strategy: string
        }
        Update: {
          assigner_role?: string
          backup_user?: string | null
          created_at?: string
          id?: string
          milestone_id?: string | null
          remark?: string | null
          role_required?: string | null
          scope_owner_role?: string
          status?: string | null
          target_user?: string
          task_id?: string | null
          task_type?: string | null
          team_id?: string
          template_id?: string | null
          updated_at?: string
          workload_strategy?: string
        }
        Relationships: []
      }
      vessels: {
        Row: {
          active: boolean | null
          carrier_id: string | null
          created_at: string | null
          id: string
          imo_number: string | null
          schedule: string | null
          updated_at: string | null
          vessel_id: string
          vessel_name: string | null
          voyage_number: string | null
        }
        Insert: {
          active?: boolean | null
          carrier_id?: string | null
          created_at?: string | null
          id?: string
          imo_number?: string | null
          schedule?: string | null
          updated_at?: string | null
          vessel_id: string
          vessel_name?: string | null
          voyage_number?: string | null
        }
        Update: {
          active?: boolean | null
          carrier_id?: string | null
          created_at?: string | null
          id?: string
          imo_number?: string | null
          schedule?: string | null
          updated_at?: string | null
          vessel_id?: string
          vessel_name?: string | null
          voyage_number?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "vessels_carrier_id_fkey"
            columns: ["carrier_id"]
            referencedRelation: "carriers"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      binary_quantize: {
        Args: { "": string } | { "": unknown }
        Returns: unknown
      }
      halfvec_avg: {
        Args: { "": number[] }
        Returns: unknown
      }
      halfvec_out: {
        Args: { "": unknown }
        Returns: unknown
      }
      halfvec_send: {
        Args: { "": unknown }
        Returns: string
      }
      halfvec_typmod_in: {
        Args: { "": unknown[] }
        Returns: number
      }
      hnsw_bit_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      hnsw_halfvec_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      hnsw_rdsvec_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      hnsw_sparsevec_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      hnswhandler: {
        Args: { "": unknown }
        Returns: unknown
      }
      ivfflat_bit_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      ivfflat_halfvec_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      ivfflathandler: {
        Args: { "": unknown }
        Returns: unknown
      }
      ivfrabitq_vector_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      l2_norm: {
        Args: { "": unknown } | { "": unknown }
        Returns: number
      }
      l2_normalize: {
        Args: { "": string } | { "": unknown } | { "": unknown }
        Returns: unknown
      }
      rds_float_normalize_i16: {
        Args: { "": unknown }
        Returns: unknown
      }
      rds_vector_norm: {
        Args: { "": string }
        Returns: number
      }
      sparsevec_out: {
        Args: { "": unknown }
        Returns: unknown
      }
      sparsevec_send: {
        Args: { "": unknown }
        Returns: string
      }
      sparsevec_typmod_in: {
        Args: { "": unknown[] }
        Returns: number
      }
      vector_avg: {
        Args: { "": number[] }
        Returns: string
      }
      vector_dims: {
        Args: { "": string } | { "": unknown }
        Returns: number
      }
      vector_norm: {
        Args: { "": string }
        Returns: number
      }
      vector_out: {
        Args: { "": string }
        Returns: unknown
      }
      vector_send: {
        Args: { "": string }
        Returns: string
      }
      vector_typmod_in: {
        Args: { "": unknown[] }
        Returns: number
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
