import { useMemo, useState } from "react";
import { CheckCircle2, ExternalLink, Inbox, UsersRound } from "lucide-react";
import type { ActionRegistryItem, CurrentUser, TaskDefinition, TaskInstance, WorkGroup } from "@/types";
import { findPage } from "@/app/pageCatalog";
import { getCurrentLanguage, t, type Language } from "@/lib/i18n";
import { loadState, saveState } from "@/lib/store";

type TaskQueuePageProps = {
  currentUser: CurrentUser;
  mode: "my" | "team";
};

const queueText = {
  zh: {
    myTitle: "我的待办",
    teamTitle: "团队待办",
    subtitle: "由 Action-first workflow simulation 生成的运行态任务。",
    task: "任务",
    action: "Action",
    object: "业务对象",
    assignment: "分配",
    target: "目标页面",
    sla: "SLA",
    complete: "完成",
    noData: "暂无生成的任务。请在工作流配置的 Simulation 中先生成 Task Instances。",
  },
  en: {
    myTitle: "My Tasks",
    teamTitle: "Team Tasks",
    subtitle: "Runtime tasks generated by the Action-first workflow simulation.",
    task: "Task",
    action: "Action",
    object: "Business Object",
    assignment: "Assignment",
    target: "Target Page",
    sla: "SLA",
    complete: "Complete",
    noData: "No generated tasks yet. Generate Task Instances in Workflow Config / Simulation first.",
  },
} satisfies Record<Language, Record<string, string>>;

function statusPill(status?: string) {
  const active = status === "Open" || status === "In Progress";
  return `inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${active ? "bg-green-soft text-green" : "bg-gray-soft text-gray"}`;
}

export default function TaskQueuePage({ currentUser, mode }: TaskQueuePageProps) {
  const lang = getCurrentLanguage();
  const tx = queueText[lang];
  const [state, setState] = useState(loadState());
  const iamUser = state.users.find((user: any) => user.email?.toLowerCase() === currentUser.email.toLowerCase());
  const userId = iamUser?.id || currentUser.email;
  const workGroupIds = new Set(iamUser?.workGroupIds || []);
  const taskDefinitions: TaskDefinition[] = state.taskDefinitions || [];
  const actions: ActionRegistryItem[] = state.actionRegistry || [];
  const workGroups: WorkGroup[] = state.workGroups || [];

  const visibleTasks = useMemo(() => {
    const tasks: TaskInstance[] = state.taskInstances || [];
    if (mode === "my") {
      return tasks.filter((task) => task.assigneeUserId === userId);
    }
    return tasks.filter((task) => !!task.assigneeWorkGroupId && workGroupIds.has(task.assigneeWorkGroupId));
  }, [mode, state.taskInstances, userId, workGroupIds]);

  const taskLabel = (id?: string) => taskDefinitions.find((task) => task.id === id)?.taskName || id || "-";
  const actionOf = (id?: string) => actions.find((action) => action.id === id);
  const userLabel = (id?: string) => state.users.find((user: any) => user.id === id)?.name || id || "-";
  const groupLabel = (id?: string) => workGroups.find((group) => group.id === id)?.workGroupName || id || "-";

  const completeTask = (taskId: string) => {
    const nextState = {
      ...state,
      taskInstances: (state.taskInstances || []).map((task: TaskInstance) =>
        task.id === taskId ? { ...task, status: "Completed" as const, completedAt: new Date().toISOString() } : task,
      ),
    };
    setState(nextState);
    saveState(nextState);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-3">
        <div className="rounded-lg bg-brand-soft p-2 text-brand-strong">
          {mode === "my" ? <Inbox className="h-5 w-5" /> : <UsersRound className="h-5 w-5" />}
        </div>
        <div>
          <h2 className="text-xl font-semibold">{mode === "my" ? tx.myTitle : tx.teamTitle}</h2>
          <p className="text-sm text-muted-foreground">{tx.subtitle}</p>
        </div>
      </div>

      <div className="overflow-x-auto rounded-lg border bg-card">
        <table className="w-full min-w-[1100px] text-sm">
          <thead className="bg-gray-50">
            <tr>
              {[tx.task, tx.action, tx.object, tx.assignment, tx.target, tx.sla, t(lang, "status"), t(lang, "actions")].map((head) => (
                <th key={head} className="px-3 py-2 text-left font-medium text-muted-foreground">{head}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y">
            {visibleTasks.length === 0 ? (
              <tr><td colSpan={8} className="px-4 py-10 text-center text-muted-foreground">{tx.noData}</td></tr>
            ) : visibleTasks.map((task) => {
              const action = actionOf(task.primaryActionId);
              const page = action ? findPage(action.pageId) : null;
              return (
                <tr key={task.id} className="align-top">
                  <td className="px-3 py-2"><div className="font-medium">{taskLabel(task.taskDefinitionId)}</div><div className="text-xs text-muted-foreground">{task.id}</div></td>
                  <td className="px-3 py-2">{action?.businessLabel || action?.label || task.primaryActionId}</td>
                  <td className="px-3 py-2">{task.businessObjectType}<div className="text-xs text-muted-foreground">{task.businessObjectId}</div></td>
                  <td className="px-3 py-2">{groupLabel(task.assigneeWorkGroupId)}<div className="text-xs text-muted-foreground">{userLabel(task.assigneeUserId)}</div></td>
                  <td className="px-3 py-2">{page ? t(lang, page.label) : action?.pageId || "-"}<div className="text-xs text-muted-foreground">{action?.tabId || "-"}</div></td>
                  <td className="px-3 py-2">{task.slaDueAt || "-"}</td>
                  <td className="px-3 py-2"><span className={statusPill(task.status)}>{task.status}</span></td>
                  <td className="px-3 py-2">
                    <div className="flex gap-2">
                      <button className="inline-flex items-center gap-1 rounded-md border px-2 py-1 text-xs hover:bg-muted" title={`${action?.pageId || ""} / ${action?.tabId || ""}`}>
                        <ExternalLink className="h-3.5 w-3.5" />
                        {tx.target}
                      </button>
                      {task.status !== "Completed" && (
                        <button onClick={() => completeTask(task.id)} className="inline-flex items-center gap-1 rounded-md bg-brand px-2 py-1 text-xs text-white hover:bg-brand-strong">
                          <CheckCircle2 className="h-3.5 w-3.5" />
                          {tx.complete}
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
